# Generated by Django 3.1.7 on 2021-04-20 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('officehours', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labid', models.CharField(max_length=20)),
                ('labname', models.CharField(max_length=20)),
                ('labschedule', models.CharField(max_length=20)),
                ('labTA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(max_length=20)),
                ('coursename', models.CharField(max_length=20)),
                ('courseschedule', models.CharField(max_length=20)),
                ('coursecredits', models.CharField(max_length=20)),
                ('graders', models.CharField(max_length=20)),
                ('courseTA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.users')),
                ('labs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.lab')),
            ],
        ),
    ]
